### ISSUE TITLE
v1.0.0 Roadmap

### ISSUE THREAD

**Issue by zoton2** [speedcontrol/nodecg-speedcontrol#38]
I'd like to drag this bundle out of Release Candidate hell and into a state where I can say it's "stable" and do more serious work on it without worrying about smaller things that are really needed.

- [x] Do we *really* need the "Force Refresh Intermission" button? That should go in the graphics bundles.
- [x] Remove references/code that is related to the `generator-speedcontrol` bundle and other parts to do with the edit mode that will be scrapped.
- [x] Check for any left over/old/outdated dependencies.
- [x] Make sure all of the `graphics` related parts are removed.
- [x] Should probably remove Gaming4Good support; was used for ESA 2016 and haven't really tested it much since besides a minor change.
- [x] Make sure all the replicants/messages names are correct and descriptive.

Moving code stuff:
- [x] Remove/move all ESA related code (like `extension/esacontroller.js`).
- [x] Split donation/tracker site support into separate bundles?
- [x] Move the experimental undocumented "Twitch highlighting" code outside of this bundle due to it's unstable nature that won't be used by everyone.

runData stuff:
- [x] Make sure the `runData` object formatting/structure is in a state where we won't change it anymore (to the best I can).
- [x] Make the names/twitch/sites part of the players data in the `runData` be specific and not just "any site could be in here".
- [x] Add option to add release date/year of games to `runData`.
- [x] Add missing information of runs to the Run Player/Run Editor panels.
- [x] Add custom data to the Run Player/Run Editor panels.
- [x] Check the Player Layout panel actually works (I remember this being an issue at ESAS18).
- [x] Change/fix the add/edit run dialog to not pass information using replicants and to allow proper team support (partially #26).
- [x] Update other bundles that are important with the changes (for example `speedcontrol-simpletext`).
- [x] Make the Horaro importing of players a bit more flexible.

Documentation stuff (partially #24):
- [x] Add information about the new split off bundles for trackers.
- [x] Document all the possible replicants/messages graphic bundles can use to make it easier for people to develop their own.
- [x] Document the recent changes to the `runData` object formatting for people who need to upgrade their bundles.
- [x] Add some README information about first time use; right now we just expect users to *know* what to do after setup.
- [x] Add information about the `dev` branch to the README for anyone who cares about that.
- [x] Document Horaro schedule formatting for correct import.
- [x] Update any other loose ends/undocumented information in the README files.
- [x] Update main screenshot to something more recent.

I will add more things to this list if/when I think of them.
